### PR TITLE
Remove usage of reserved Object keyword

### PR DESCRIPTION
**Pull request by PavelJurasek**
and effectively support php 7.2

### CODE REVIEW

**Comment by Hajneej** [comment]
Hi, sorry for this late answer.

Could you please fix issues which travis discovered? Also, could you please fix its configuration? (travis.yml) . I am not sure why the PR runs smoothly in php 5.6 and 7.0 and it is not running smoothly in older versions. 

Anyway, I am not sure about the oldest php version supported by Nette, but it looks like it is php 5.6 for Nette 2.4 and php 5.4 for Nette 2.3. I am for supporting Nette 2.4. Therefore, could you please also change the dependencies in composer.json?

Thanks

**Comment by PavelJurasek** [comment]
PHP only 5.6 and higher, 7.2 fails in paypal's package, cleaned up dependencies

**Comment by Hajneej** [comment]
Thanks, it looks like they are working on it - https://github.com/paypal/PayPal-PHP-SDK/issues/1014 .

Just one thing to the cleanup - I think it is better to have '@dev' stability flag for development dependencies ('require-dev' section). Could you please add it? Otherwise, it looks ok for me and I will merge it.

**Comment by PavelJurasek** [comment]
done

**Pull request merged**
